
name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install
        shell: bash
        run:  |
          npm i
      - name: Build
        shell: bash
        run: |
          npm run compile
      - name: Lint
        shell: bash
        run: |
          npm run lint
